{
 "title": "Xn2 Example Data Set Collection",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Curve A",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "xer_ep_curve_a", "legendFormat": "{{set}}" }
   ]
  },
  {
   "title": "Curve A Dist",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "xer_ep_curve_a", "legendFormat": "{{set}}" }
   ]
  },
  {
   "title": "Curve B",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "xer_ep_curve_b", "legendFormat": "{{set}}" }
   ]
  },
  {
   "title": "Curve B Dist",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "xer_ep_curve_b", "legendFormat": "{{set}}" }
   ]
  },
  {
   "title": "Alpha Set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "xer_set_alpha{ep=\"curve_a\"}",
     "legendFormat": "{{ep}}"
    },
    {
     "expr": "xer_set_alpha{ep=\"curve_b\"}",
     "legendFormat": "{{ep}}"
    },
    {
     "expr": "xer_set_alpha{ep=\"sec\"}",
     "legendFormat": "{{ep}}"
    }
   ]
  },
  {
   "title": "Curve A Heat",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "xer_ep_curve_a{set=\"alpha\"}"
    },
    {
     "expr": "xer_ep_curve_a{set=\"beta\"}"
    },
    {
     "expr": "xer_ep_curve_a{set=\"gamma\"}"
    },
    {
     "expr": "xer_ep_curve_a{set=\"delta\"}"
    }
   ]
  },
  {
   "title": "Alpha Set Polls",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "xer_total_set_runs{set=\"alpha\"}"
    }
   ]
  },
  {
   "title": "Alpha Endpoint Polls",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "xer_total_ep_polls{set=\"delta\"}"
    }
   ]
  },
  {
   "title": "rxtx Errors Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "xer_total_send_poll_errors", "legendFormat": "{{set}}" }
   ]
  },
  {
   "title": "Beta Set Polls",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "xer_total_set_runs{set=\"beta\"}"
    }
   ]
  },
  {
   "title": "Beta Endpoint Polls",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "xer_total_ep_polls{set=\"beta\"}"
    }
   ]
  },
  {
   "title": "Gamma Polls",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "xer_total_set_runs{set=\"gamma\"}"
    }
   ]
  },
  {
   "title": "Gamma Endpoint Polls",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "xer_total_ep_polls{set=\"gamma\"}"
    }
   ]
  },
  {
   "title": "Send (to rxtx) Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "xer_total_send_poll_errors", "legendFormat": "{{set}}" }
   ]
  },
  {
   "title": "Delta Set Polls",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "xer_total_set_runs{set=\"delta\"}"
    }
   ]
  },
  {
   "title": "Delta Endpoint Polls",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "xer_total_ep_polls{set=\"delta\"}"
    }
   ]
  }
 ]
}