{
 "title": "Xn2 Operational Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "rtBeat ACKS",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 8, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rtbeat_acks_received" }
   ]
  },
  {
   "title": "rxtx messages in queue",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rxtx_messages_in_queue" }
   ]
  },
  {
   "title": "rxtx Batches",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "rxtx_tx_batches" }
   ]
  },
  {
   "title": "rtBeat Batches Received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "rtbeat_batches_received" }
   ]
  },
  {
   "title": "rxtx Messages Received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "rxtx_total_messages_received" }
   ]
  },
  {
   "title": "rtBeat Message Parsed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "rtbeat_messages_parsed" }
   ]
  },
  {
   "title": "rxtx Tx Fails",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "rxtx_tx_fails" }
   ]
  }
 ]
}